title: Core
author:
  name: 'Ryan Sipes'
  email: dev@mycroft.ai
taxonomies:
  - category
  - tag
metadata:
  description: 'Docs for Mycroft'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
